### Algorritmo de planificacion de procesos 

Los sistemas operativos utilizan cadenas de Markov para modelar el comportamiento de los procesos y planificar su ejecución. Los estados pueden representar diferentes estados de ejecución, como listo, en ejecución, bloqueado, etc.

En el contexto de los algoritmos de planificación de procesos, una cadena de Markov puede ser utilizada para modelar el comportamiento dinámico de los procesos en un sistema operativo. Supongamos que tenemos tres estados principales que representan el estado de ejecución de un proceso en un sistema:

Listo (Ready): El proceso está listo para ejecutarse pvgero aún no se le ha asignado tiempo de CPU.
En Ejecución (Running): El proceso está actualmente en ejecución y utilizando la CPU.
Bloqueado (Blocked): El proceso está bloqueado, por ejemplo, esperando la finalización de una operación de entrada/salida.


Podemos representar estas transiciones entre estados mediante una matriz de transición de estados. La siguiente matriz de transición de estados es un ejemplo simple:

In [22]:
import numpy as np

# Definir estados
estados = ["INICIANDO", "EN EJECUCION", "RECARGA", "FALLA"]
# índices estados
indice_estado = {estado: i for i, estado in enumerate(estados)}

# matriz de transición de estados
transicion_estados = np.array([
    #I    E      R     F     
    [0.03, 0.90, 0.00, 0.07],  # INICIANDO
    [0.05, 0.90, 0.04, 0.01],  # EN EJECUCION
    [0.00, 0.90, 0.00, 0.10],  # RECARGA
    [1.00, 0.00, 0.00, 0.00],  # FALLA
    
])



# Simulacion de multiples transiciones de estados
num_transiciones = 10

# Estado inicial
estado_actual = estados[0]
print(f"Estado inicial: {estado_actual}")

for _ in range(num_transiciones):
   
    # Obtener el índice del estado actual
    indice_actual = indice_estado[estado_actual]
        
    # Elegir el próximo estado según la matriz de transición
    eleccion = np.random.multinomial(1, transicion_estados[indice_actual])

    # Obtener el índice del próximo estado
    indice_proximo_estado = np.argmax(eleccion)

    # Obtener el nombre del próximo estado
    proximo_estado = estados[indice_proximo_estado]

    # Actualizar el estado actual para el próximo paso
    estado_actual = proximo_estado
        
    print("Estado actual", proximo_estado)

print("Simulación terminada")
print("------")

Estado inicial: INICIANDO
Estado actual EN EJECUCION
Estado actual INICIANDO
Estado actual EN EJECUCION
Estado actual EN EJECUCION
Estado actual EN EJECUCION
Estado actual EN EJECUCION
Estado actual RECARGA
Estado actual FALLA
Estado actual INICIANDO
Estado actual EN EJECUCION
Simulación terminada
------


In [48]:
transicion_estados_paciente = np.array([
    # C    S        E
    [0.60, 0.30, 0.10 ],  # Critico
    [0.40, 0.40, 0.20 ],  # Serio
    [0.10, 0.40, 0.50, ],  # Estable
  
    
])

n  = 2
# PROCEDIMIENTO
pn = np.linalg.matrix_power(transicion_estados_paciente,n)

# SALIDA
print(pn)




[[0.49 0.34 0.17]
 [0.42 0.36 0.22]
 [0.27 0.39 0.34]]


In [49]:
# Calcular la probabilidad de pasar de EN EJECUCIÓN a FALLO en el instante 3
probabilidad_fallo_en_instante_3 = np.linalg.matrix_power(transicion_estados_paciente, 2)[0][2]

print(f"La probabilidad de pasar de critico  a estable en el instante 3 es: {probabilidad_fallo_en_instante_3}")


La probabilidad de pasar de critico  a estable en el instante 3 es: 0.16999999999999998


In [66]:
import numpy as np

# Definir estados
estados_paciente = ["CRITICO", "SERIO", "ESTABLE"]
# índices estados
indice_estado_paciente = {estado: i for i, estado in enumerate(estados_paciente)}

# Matriz de transición de estados de pacientes
transicion_estados_paciente = np.array([
    # C    S        E
    [0.60, 0.30, 0.10],  # Critico
    [0.40, 0.40, 0.20],  # Serio
    [0.10, 0.40, 0.50],  # Estable
])

# Estado inicial (puede ser aleatorio o definido)
estado_actual_paciente = "CRITICO"

# Simulación de transiciones durante 7 días
num_dias = 7

for dia in range(1, num_dias + 1):
    # Obtener el índice del estado actual
    indice_actual_paciente = indice_estado_paciente[estado_actual_paciente]

    # Elegir el próximo estado según la matriz de transición
    eleccion_paciente = np.random.multinomial(1, transicion_estados_paciente[indice_actual_paciente])

    # Obtener el índice del próximo estado
    indice_proximo_estado_paciente = np.argmax(eleccion_paciente)

    # Obtener el nombre del próximo estado
    proximo_estado_paciente = estados_paciente[indice_proximo_estado_paciente]

    # Actualizar el estado actual para el próximo día
    estado_actual_paciente = proximo_estado_paciente

    # Mostrar el estado del paciente en cada día
    print(f"Día {dia}: Paciente en estado {estado_actual_paciente}")

print("Simulación de 7 días terminada")


Día 1: Paciente en estado ESTABLE
Día 2: Paciente en estado ESTABLE
Día 3: Paciente en estado ESTABLE
Día 4: Paciente en estado SERIO
Día 5: Paciente en estado SERIO
Día 6: Paciente en estado ESTABLE
Día 7: Paciente en estado ESTABLE
Simulación de 7 días terminada
